# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            분석하는 던붕이
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              "http://gauguin94.github.io"
baseurl:          /gauguin94.github.io

author:
  name:           'Kyeong Nam, Ko'
  url:            http://gauguin94.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://https://github.com/Gauguin94
